name: Run Python tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          path: Arcan-Backend

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          cd Arcan-Backend
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Configure PYTHONPATH
        run: echo "PYTHONPATH=$GITHUB_WORKSPACE/Arcan-Backend" >> $GITHUB_ENV

      - name: Copy CI environment variables
        run: cp Arcan-Backend/tests/.env.ci Arcan-Backend/.env

      - name: Run tests with pytest
        run: |
          cd Arcan-Backend
          pytest tests/ --disable-warnings